export enum EmailType {
  WELCOME = 'WELCOME',
  PASSWORD_RESET = 'PASSWORD_RESET',
  OTP = 'OTP',
  NOTIFICATION = 'NOTIFICATION',
  ORDER_CONFIRMATION = 'ORDER_CONFIRMATION',
  SHIPMENT_TRACKING = 'SHIPMENT_TRACKING',
  REPORT = 'REPORT',
  OTHER = 'OTHER'
}
