export enum ReasonType {
  DAMAGE = 'DAMAGE',
  THEFT = 'THEFT',
  COUNT_ERROR = 'COUNT_ERROR',
  EXPIRED = 'EXPIRED',
  QUALITY_ISSUE = 'QUALITY_ISSUE',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  OTHER = 'OTHER'
}
